Quantum = RegisterMod("Quantum Pack", 1)

---@type SaveManager
Quantum.save = include("save_manager")
Quantum.save.Init(Quantum)

Quantum.UTILS = include("quantum.utils")
Quantum.QUEUE = include("quantum.sys_queue")

include("quantum.item_pickupreroll")
include("quantum.item_removeoptions")
include("quantum.item_hydrokinesis")
include("quantum.item_horserpills")
include("quantum.item_cultfollowing")
include("quantum.item_sacrificer")
include("quantum.item_enemylink")
include("quantum.item_activegulp")
include("quantum.item_coincollection")
include("quantum.item_wormbucket")
include("quantum.item_artificalbloom")
include("quantum.item_roomhack")
include("quantum.item_singularity")
include("quantum.item_dicedmeat")
include("quantum.item_jestersdeck")
include("quantum.item_d4sale")
include("quantum.trinket_orbitworm")
include("quantum.trinket_trailworm")
include("quantum.trinket_clumpedpenny")
include("quantum.trinket_trophy")